### ISSUE TITLE
Feature request: Add to modifers map

### ISSUE THREAD

**Issue by jrowny** [jimmynicol/image-resizer#10]
It'd be nice if I could add to the modifiers map/parse somehow so I could add arguments for custom filters, i.e. r for "rotate". r180 for example, would flip an image.

**Comment by ernestopye** [comment]
+1 - I forked the repo wanting to add a "padding" modifier, to maintain dimensions without cropping and just add white/black bars on the top/bottom or left/right to ensure the image.

**Comment by genexp** [comment]
I came upon this ticket too, while looking to see if this supports conversion (we have a bunch of PNGs from an API we use that we have to convert to JPG).

**Comment by jimmynicol** [comment]
closing this ticket. also not looking to add conversion as it is outside of the scope of this project.
