### ISSUE TITLE
feature request: support any image source on-the-fly 

### ISSUE THREAD

**Issue by mariusa** [jimmynicol/image-resizer#16]
Hello,

Would it be possible to make this work same as http://www.sencha.com/learn/how-to-use-src-sencha-io/ ?

That is, accessing 
http://my-deploy.herokuapp.com/h500/http://whatever.com/image.jpg
will render the image from whatever.com at 500px.

I'm confused by required Amazon credentials (minimum required variables). They should be optional, unless one enables cache storage with Amazon.

Thanks

**Comment by madshobye** [comment]
Hey Marlusa - could you share the onthefly.js - the pastebin does not work anymore and I would love to make it work.

**Comment by mariusa** [comment]
Here it is: http://we.tl/4EUq6C46cI

**Comment by jgillman** [comment]
@mariusa Hey, sorry to be a pain, but I would really love to see it as well. Could you throw it into a private gist instead of a service that expires links?

**Comment by mariusa** [comment]
Sure!
https://gist.github.com/mariusa/a0c6851eb1c1f4e6a865
