### ISSUE TITLE
Constantly Missing from Cloudfront cache - possibly due to incorrect cache headers from image-resizer?

### ISSUE THREAD

**Issue by J-Gonzalez** [jimmynicol/image-resizer#27]
I've got my Cloudfront Cache Behavior settings to Use Origin Cache Headers from my Image Resizer origin.  I however keep getting Misses from Cloudfront as if it's not caching the files correctly. I'm not sure if this is due to me sending the files to S3 originally with incorrect cache headers and image-resizer is just passing them on, or if I've configured image resizer incorrectly.  Ideally I'd like to be able to set the cache expiry time in image resizer. I'm deployed to Heroku.

I've tried using IMAGE_EXPIRY node env (and setting to 7776000) and before also had the following code in my image servers index.js:
```
response.setHeader('Cache-Control', 'public, max-age=' + 6048000);
```

It seems that some images are Hits from Cloudfront, while many others are a Miss, even after refreshing the page multiple times, they still miss.

**Comment by jimmynicol** [comment]
@J-Gonzalez, I have been digging into this. I took a look at the link you showed and was not seeing any misses from the cache. Have you made any modifications that may have gotten this working? I would love to be able to fix anything that was missing.

I have also been re-reading this: 

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html

And I am fairly certain the default cache behaviour from `image-resizer` is doing what it should be. We set the following headers: `Expires`, `Cache-Control`, `Vary`, `Last-Modified`.

Anyway please let me know if this is still an issue, or if you discovered anything note worthy.

**Comment by J-Gonzalez** [comment]
This is still an issue and I'm not sure if it's on my side or not.  I went back using image-resizer "defaults" and setting my expiry to: 7776000, yet every day or so, cloudfront is needing to hit the origin, and imge-resizer is having to RE-generate all the images.  Cloudfront is set up to "Use Origin Cache Headers".

A link you can look at is here: https://www.tickeri.com/events - Some images miss pretty constantly, others are a HIT but only last a day or so before needing to be regenerated by image-resizer.

Any ideas?

**Comment by jimmynicol** [comment]
Hi @J-Gonzalez,

Unfortunately I think this might be to do with your CDN. From my poking around on your page I could only see a couple of missing images and that was on the individual event pages and only the first time. 

Often a CDN will [evict objects](http://docs.aws.amazon.com/AmazonCloudFront/2010-11-01/DeveloperGuide/Eviction.html) that are not getting a lot of traffic, forcing them to be refetched from their custom origin. So if your site is under development and not getting a lot traffic then it is possible this is happening and it may get better as your traffic improves.

As I mentioned previously I cant see anything straight up that may causing this, the headers look to be set correctly. Sorry this is happening, I have only ever used this behind a moderately high traffic site in a production setting.

I can only suggest you either live with this for the short term (ie till your traffic increases) or you investigate some of the competitors like Akamai or Cloudflare. I do not have direct experience with either of them so I cant comment directly on whether or not this may alleviate this issue.

Good luck.

**Comment by J-Gonzalez** [comment]
Thanks for the response Jimmy - This is on a site with over a 150,000 pageviews per month so I know it's not related to that.  We've had many reports of the images having to be re-created often, and it happens to me daily.  I'll keep messing with this issue and seeing if it's related to S3, Cloudfront, or image-resizer.

**Comment by jimmynicol** [comment]
No problems, love to hear if you find anything helpful.

**Comment by dionbosschieter** [comment]
Hi @J-Gonzalez,

I am having the same problems with AWS CloudFront. The headers are set to expire in a year. 
I wonder if you found a solution to your problem. Or perhaps you know why cloudfront is missing so often.

**Comment by eivindvr** [comment]
Im having the same problem!

**Comment by JayRizzo** [comment]
I found that this is related to HTTP vs. HTTPS.

Where the site is HTTPS 
but the links using HTTP that you CURL will showcase this issue

```
Example: 

curl -svoI http://TEST_URL.com/SOME/LINK.png

// VS.

curl -svoI https://TEST_URL.com/SOME/LINK.png
```
You will see the difference.
