### ISSUE TITLE
identify: no identify

### ISSUE THREAD

**Issue by knightcode** [jimmynicol/image-resizer#34]
```
[resizer] new stream created! 
[resizer] s3 - 169ms
[resizer] identify: no identify 
[resizer] Error: spawn ENOENT 
```

Not very helpful output

**Comment by jimmynicol** [comment]
At a guess I would imagine `graphicsmagick` is not installed. The `gm` library doesnt give us better errors about the missing dependency at all (at least it didnt previously). Hopefully I can address this better when I land the PR to bring in the `sharp` library which doesnt use `graphicsmagick`.

**Comment by knightcode** [comment]
Yep. That did it. Maybe add a line or two to the documentation declaring the dependency?

**Comment by jimmynicol** [comment]
It is listed in the README under Dependencies, but once I land the vips/sharp branch I will make more reference to it as a lot of people seem to be missing it.
