### ISSUE TITLE
ENOMEM and auto relauching

### ISSUE THREAD

**Issue by knightcode** [jimmynicol/image-resizer#35]
I have a workflow where a bulk of new images get uploaded to S3 at a time. This causes an spike in traffic to the server, and it's running out of memory..... I can sort of tolerate a crash, but I can't tolerate that gulp steps in and keeps the process running in a failed state.

I already have the process launched as a daemon in the server, so I don't really need gulp doing anything. I'm a bit confused how the call to env() in gulpfile.js sets the config correctly since it seems like all the vars seem to be pulled from environment_vars.js, at least in test.js. Is there a good way avoid using gulp and not store env vars in a repo?

**Comment by jimmynicol** [comment]
So gulp is only for development, it is simply just a task runner to help with tests and linting etc. You should not use it in a production setting. 

You should create a new instance of the app with the command line tool `image-resizer new`. Then if you are going to run the app by your self (ie not on Heroku) then it would be started by `node index.js`. The `env` function in the gulp file is simply just a convenient way to load in environment variables along the lines of `export NODE_ENV=production`.

Configuration of app on Heroku is all done via environment variables so I used that paradigm for `image-resizer`. You would manage your server config in the same fashion by setting each of the vars that is important to you, keeping them out of the repo.

Hope this helps.

**Comment by knightcode** [comment]
Thanks.

But seems a lied about tolerating the ENOMEM crashes given how frequently the images leave Cloudfront. The easiest solution seems to be to store the resized images back in S3 as another cache. Both putObject and upload are complaining about the stream object returned, though. Is there any way you can implement a Readable stream?
