### ISSUE TITLE
Original image request hangs

### ISSUE THREAD

**Issue by jgillman** [jimmynicol/image-resizer#36]
As [mentioned in the 'sharp' pull request](https://github.com/jimmynicol/image-resizer/pull/31#issuecomment-74457293) requesting the original image without any modifiers seems to hang.

For example, the request `http://localhost:3003/test.png` does not resolve until it either times out or the user kills the request in the browser. When that happens the following is output in the console/logs:

```
GET /test.png - - ms - -
```

**Comment by jimmynicol** [comment]
Fixed in the latest `sharp` branch.
