### ISSUE TITLE
External source image expiry

### ISSUE THREAD

**Issue by risul** [jimmynicol/image-resizer#44]
In readme, there is a reference to env variable: SOCIAL_IMAGE_EXPIRY, but when investigating source code for facebook plugin (https://github.com/jimmynicol/image-resizer/blob/master/src/streams/sources/facebook.js#L26), I see that image expiry is set to env variable IMAGE_EXPIRY_SHORT which means SOCIAL_IMAGE_EXPIRY is not used anywhere in the code.. am I correct?

**Comment by jimmynicol** [comment]
Sorry about that, yes IMAGE_EXPIRY_SHORT is the one to use. You can however set this in custom sources if you want pretty easily. An example is in the [Facebook source](https://github.com/jimmynicol/image-resizer/blob/master/src/streams/sources/facebook.js#L26).
