### ISSUE TITLE
JPG image quality seems to be stuck at 80

### ISSUE THREAD

**Issue by jgillman** [jimmynicol/image-resizer#50]
[This bit of code](https://github.com/jimmynicol/image-resizer/blob/2062762b13d805feacadf24beddf2fbfcf492a71/src/streams/optimize.js#L31) looks like it should be setting the quality, but when I check images that come out the other side their quality is always `80`.

In my .env I have `IMAGE_QUALITY` set to `99`. I'm using ImageMagick's `identify` utility to grab the image quality.

In my particular case the images are getting crushed in such a way that they really look terrible (probably have to click to see the full size):
 
![compressed](https://cloud.githubusercontent.com/assets/172217/7244220/1e6524fc-e78d-11e4-88ab-50c25133ae7d.jpg)

**Comment by jimmynicol** [comment]
Hey @jgillman,

I think this was because I missed `IMAGE_QUALITY` in the environment vars. I have made this update and made sure the values are cast as numbers so you shouldnt be seeing this issue again.

`v1.0.1` has these fixes.

**Comment by jgillman** [comment]
Nice! Thanks for the quick fix.
