### ISSUE TITLE
Feature: Content Types

### ISSUE THREAD

**Issue by genexp** [jimmynicol/image-resizer#55]
Currently, the image-resizer only allows files that have a white-listed file extension (jpg, png, etc.)  However, many image hosts ignore file extensions.  As an example, here's a video from popular video host Ooyala:

    http://ec.c.ooyala.com/Fpbzl1dTo65q-IuenkPBkqSLXlbKFYAz/3Gduepif0T1UGY8H4xMDoxOjBzMTt2bJ

The image resizer should probably not check file extension on a request, rather, it should check the content type of the response and pass it to the various filters.  

Further, it would great if we could change the type within a filter.  For example:

````
module.exports = function(image, callback) {

  // create the sharp object
  var r = sharp(image.contents);

  // apply the filter and pass on the stream
  r.toFormat(sharp.format.png).stream(callback);
};
````

**Comment by jimmynicol** [comment]
You should try out `v1.2.0` as the handling of the image type checks should help with this.
