### ISSUE TITLE
Building image resizer on windows

### ISSUE THREAD

**Issue by nastassiar** [jimmynicol/image-resizer#56]
I've been having issues trying to build image-resizer on windows and deploy to Heroku. 

The npm install instructions don't work for me. I get errors saying sharp is not supported on windows x64. 

So instead I tried the following:

First I cloned the repository. 
> heroku create
> heroku config:set NODE_ENV=development
> heroku config:set BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi
> heroku ps:scale web=1
> git push heroku master

When I ran the push command I got an error stating that the .buildfile could not be found so I manually created it based on the template.
I then got an error regarding npm start when I tried to run again so I manually created the Procfile based on the template. 
The when I run the push command it buillt correctly, but when I ran > heroku open and looked at the logs. I had the following errors:
module.js 338
    throw: Err;
Error: Cannot find module 'app/bin/image-resizer.js' 
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Function.Module.runMain (module.js:501:10)

I realize now that this is because I never built image-resizer is there a way to do this on Heroku or something I am doing wrong in windows?

**Comment by jimmynicol** [comment]
Unfortunately I dont have a windows test machine to test this with sorry. A few things I can suggest though.

 - are you using the cli tool (`image-resizer new`) to create your project? if not you may want to try that.
 - also you will need libvips installed on your machine prior to running `npm install` as sharp will need to compile against the version you have installed. windows has a different installation procedure which is listed [here](http://sharp.dimens.io/en/stable/install/#windows).
