### ISSUE TITLE
Throws 500 when should be returning 404?

### ISSUE THREAD

**Issue by saintberry** [jimmynicol/image-resizer#57]
Hey,

I've noticed that if a request comes in for an image format that's not supported:
```
Image.validFormats = ['jpeg', 'jpg', 'gif', 'png'];
````
Image-Resizer will throw a 500 error. This seems like incorrect behaviour to me. If a document doesn't exist on S3, regardless of the extension shouldn't a 404 be returned?

If the document does exist, but is not a valid image format, then the service should return a 500.

I'd be interested to hear thoughts.

**Comment by asilvas** [comment]
+1

**Comment by jackmurphy** [comment]
+1

**Comment by jimmynicol** [comment]
This has been fixed with `v1.2.0`.
