### ISSUE TITLE
Building Sharp on Heroku requires Cedar-14

### ISSUE THREAD

**Issue by J-Gonzalez** [jimmynicol/image-resizer#66]
To build sharp, "GCC version 4.6+ is required".  The outdated Cedar-10 stack has GCC 4.4 only.  Heroku apps must update to the Cedar-14 stack to use the newer version of image-resizer that user sharp instead of GM.  Readme should be updated to detail this required change.

https://devcenter.heroku.com/articles/cedar-ubuntu-packages

**Comment by jimmynicol** [comment]
@J-Gonzalez you are correct, see #28. I will update the readme to reflect this.
