### ISSUE TITLE
Image quality after resize

### ISSUE THREAD

**Issue by lovec** [jimmynicol/image-resizer#70]
I have problems with quality of image after resize. Here are 3 images:

1. resize with current 1.2.0 version, quality set to 100
![resize-v1 2 0](https://cloud.githubusercontent.com/assets/1532335/9427098/3ce12e26-4994-11e5-8b51-26a933c51ea7.jpg)

2. resize with super old version (sep 2013), that used graphics magic library (quality also 100)
![image-using-graphicsmagic](https://cloud.githubusercontent.com/assets/1532335/9427099/40cb31f8-4994-11e5-8ac2-15631800bcc2.jpg)

3. For comparison, resize done by PHP
![php-resize](https://cloud.githubusercontent.com/assets/1532335/9427100/433a4780-4994-11e5-854b-2dbfc8759957.jpg)

This is the original image
![original](https://cloud.githubusercontent.com/assets/1532335/9427103/7d64f0b8-4994-11e5-8f69-3c309453d8e6.jpg)

Is there some quality configuration that I am missing?

**Comment by OriginalEXE** [comment]
Hi,

I just tested this with your assets and indeed, I get the same (crappy) result with your image and a couple of mines, image quality set to 100.

It seems like the image loses a bit of sharpness.

**Comment by lovell** [comment]
Hello, the [interpolateWith](http://sharp.dimens.io/en/stable/api/#interpolatewithinterpolator) method is your friend here - see also https://github.com/lovell/sharp/issues/261

**Comment by OriginalEXE** [comment]
Hi @lovec, thanks to the @lovell here from the sharp repo I managed to get much better results.

Apparently image-resizer uses bilinear interpolation by default (that's the default value of the sharp library and image-resizer does not change it anywhere).

So what I di was go to image-resizer/streams/resize.js and after every .resize() call you call this as well:
`.interpolateWith(sharp.interpolator.bicubic).sharpen()`

This improved the output quality noticeably, while still giving good compression.

**Comment by jimmynicol** [comment]
@lovell thanks so much for the info, I will integrate this into the library as it seems to be the sensible default.

**Comment by lovec** [comment]
Thanks!
