### ISSUE TITLE
Where are modified resources cached?

### ISSUE THREAD

**Issue by OriginalEXE** [jimmynicol/image-resizer#71]
Hi,

thank you for this awesome library, had some troubles setting it up but eventually succeeded, it was well worth it :)

Since I am in the process of development, I am running this on a local server and I was wondering, are modified images saved anywhere (and later checked for their existence) or is that feature disabled for the local source?

Another thing, since I eventually plan on using s3 (will be my first time), you mention in your docs that images are no longer sent back to the S3 storage, but instead, and I quote, "The full power of the CDN is used for storing the modified images. This greatly improves performance both on the server side and client side.".

Could you maybe explain in a bit more details how are modified images stored when using S3, if they are not sent back to the server?

Thanks again for crafting this awesome library, appreciated :)

**Comment by J-Gonzalez** [comment]
@OriginalEXE:

S3 is used as a place to store your original (source) images. Image Resizer, when configured to use S3 as a source will look for images from your source location.  For example:

1.   You request myimageserver.com/w200/myimage.jpg
2.  Image resizer will look for myimage.jpg (the source) in S3, and then transform it to use width 300.
3.  Image resizer will display you the resized image.

The resized image is NOT saved anywhere by image resizer, as this is not the job of image resizer.  Using a CDN here is what will increase performance.  A CDN will automatically store the images requested for you.

For example:

1.  You create a CDN (like Amazon Cloudfront).  You get a URL for your CDN.  http://myimages.cloudfront.amazon.com.
2.  You request your image at the CDN url, like http://myimages.cloudfront.amazon.com/w200/myimage.jpg
3.   If Cloudfront has the resized image, it will serve it to you.  If it does NOT, Cloudfront is configured to request the image at http://myimageserver.com/w200/myimage.jpg (and will go through the steps in the previous example)
4.   Cloudfront will store this resized image automatically in the CDN
5.   Cloudfront will serve the resized image to you

Hopefully this makes it clearer on the different moving parts you'll need when using image-resizer.  While it sounds complicated and like it has a lot of moving parts, it's pretty simple to implement, as the CDN configuration is simple.

**Comment by OriginalEXE** [comment]
Oh man, I am so dumb.

This whole time I am forgetting that S3 is not a CDN, and how CDN works. Braindead.

Thank you very much for a detailed explanation, much appreciated, all clear now :)

**Comment by jimmynicol** [comment]
@J-Gonzalez thanks for the detailed explanation. 

@OriginalEXE the premise behind this design is to have as few moving parts as possible. The CDN is just a location aware caching layer and it made sense to leverage that as much as possible.

It is worthy of note however that despite setting the appropriate expiry headers CDNs will still age out content that is not being requested frequently. There is little you can do to avoid this. `image-resizer` is optimised however to generate the source content as quickly as possible (see the move to `sharp`) to avoid any issues in this regard.
