### ISSUE TITLE
Make it possible to optimize image only, without applying other modifiers.

### ISSUE THREAD

**Issue by OriginalEXE** [jimmynicol/image-resizer#72]
Hello,

right now it's not possible to only optimize the image. For example, if you only link to image using a q90 prefix, it will not return the image at all.

I'm not sure if this is intentional or not, but I think it makes sense to be able to only reduce the quality of the image without modifying it further?

Thanks

**Comment by jimmynicol** [comment]
Good catch, thanks. `v1.3.0` fixes this issue.
