### ISSUE TITLE
Update Sharp version requirement

### ISSUE THREAD

**Issue by OriginalEXE** [jimmynicol/image-resizer#73]
Hello,

it seems like there is an issue with the version of Sharp required by this module. When I npm install Sharp package separately, it build fine, but when image-resizer tries to install it as a dependency, the build fails.

To install it, I had to modify the version of Sharp required by image-resizer package.json module in ~.npm cache.

**Comment by jimmynicol** [comment]
Hi @OriginalEXE,

Any chance you can provide more information about this? I am not able to replicate this at all, either with `v0.10.1` which is the current version required by `image-resizer` or the newer version `v0.11.3`. I am going to bump the version in the next release but from my tests I cant see an issue with this.

**Comment by OriginalEXE** [comment]
Hi,

here are the logs:

	12285 verbose about to build /var/www/playground/node_modules/image-resizer
	12286 verbose unlock done using /home/originalexe/.npm/_locks/image-resizer-89a535f21d4a8313.lock for /var/www/playground/node_modules/image-resizer
	12287 verbose stack Error: sharp@0.10.1 install: `node-gyp rebuild`
	12287 verbose stack Exit status 1
	12287 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
	12287 verbose stack     at emitTwo (events.js:87:13)
	12287 verbose stack     at EventEmitter.emit (events.js:172:7)
	12287 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
	12287 verbose stack     at emitTwo (events.js:87:13)
	12287 verbose stack     at ChildProcess.emit (events.js:172:7)
	12287 verbose stack     at maybeClose (internal/child_process.js:818:16)
	12287 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
	12288 verbose pkgid sharp@0.10.1
	12289 verbose cwd /var/www/playground
	12290 error Linux 3.19.0-26-generic
	12291 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "image-resizer"
	12292 error node v4.1.2
	12293 error npm  v2.14.4
	12294 error code ELIFECYCLE
	12295 error sharp@0.10.1 install: `node-gyp rebuild`
	12295 error Exit status 1
	12296 error Failed at the sharp@0.10.1 install script 'node-gyp rebuild'.
	12296 error This is most likely a problem with the sharp package,
	12296 error not with npm itself.
	12296 error Tell the author that this fails on your system:
	12296 error     node-gyp rebuild
	12296 error You can get their info via:
	12296 error     npm owner ls sharp
	12296 error There is likely additional logging output above.
	12297 verbose exit [ 1, true ]
	12298 verbose unbuild node_modules/image-resizer/node_modules/sharp
	12299 info preuninstall sharp@0.10.1
	12300 info uninstall sharp@0.10.1
	12301 verbose unbuild rmStuff sharp@0.10.1 from /var/www/playground/node_modules
	12302 verbose unbuild rmStuff in /var/www/playground/node_modules/image-resizer/node_modules
	12303 info postuninstall sharp@0.10.1
	12304 silly gentlyRm /var/www/playground/node_modules/image-resizer/node_modules/sharp is being purged from base /var/www/playground
	12305 verbose gentlyRm don't care about contents; nuking /var/www/playground/node_modules/image-resizer/node_modules/sharp
	12306 silly vacuum-fs purging /var/www/playground/node_modules/image-resizer/node_modules/sharp
	12307 silly vacuum-fs quitting because other entries in /var/www/playground/node_modules/image-resizer/node_modules
	12308 verbose unbuild node_modules/image-resizer
	12309 info preuninstall image-resizer@1.2.1
	12310 info uninstall image-resizer@1.2.1
	12311 verbose unbuild rmStuff image-resizer@1.2.1 from /var/www/playground/node_modules
	12312 silly gentlyRm /var/www/playground/node_modules/.bin/image-resizer is being gently removed
	12313 silly gentlyRm verifying /var/www/playground is an npm working directory
	12314 silly gentlyRm containing path /var/www/playground is under npm's control, in /var/www/playground
	12315 silly gentlyRm deletion target /var/www/playground/node_modules/.bin/image-resizer is under /var/www/playground
	12316 verbose gentlyRm vacuuming from /var/www/playground/node_modules/.bin/image-resizer up to /var/www/playground
	12317 info postuninstall image-resizer@1.2.1
	12318 silly gentlyRm /var/www/playground/node_modules/image-resizer is being purged from base /var/www/playground
	12319 verbose gentlyRm don't care about contents; nuking /var/www/playground/node_modules/image-resizer
	12320 silly vacuum-fs purging /var/www/playground/node_modules/image-resizer
	12321 silly vacuum-fs removing /var/www/playground/node_modules
	12322 silly vacuum-fs finished vacuuming up to /var/www/playground

From the terminal:

	> sharp@0.10.1 install /var/www/playground/node_modules/image-resizer/node_modules/sharp
	> node-gyp rebuild

	make: Entering directory `/var/www/playground/node_modules/image-resizer/node_modules/sharp/build'
	  CXX(target) Release/obj.target/sharp/src/common.o
	  CXX(target) Release/obj.target/sharp/src/utilities.o
	In file included from ../src/utilities.cc:4:0:
	../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
	   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
	                           ^
	../node_modules/nan/nan.h:319:17: error: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
	   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
	                 ^
	../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
	   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
	                           ^
	../node_modules/nan/nan.h:334:27: error: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
	   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
	                           ^
	../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
	     , node::smalloc::FreeCallback callback
	             ^
	../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
	     , node::smalloc::FreeCallback callback
	                                   ^
	../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
	../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
	         v8::Isolate::GetCurrent(), data, length, callback, hint);
	                                                  ^
	../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
	         v8::Isolate::GetCurrent(), data, length, callback, hint);
	                                                            ^
	../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
	../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
	     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
	                                                                   ^
	../node_modules/nan/nan.h:768:67: note: candidates are:
	In file included from ../node_modules/nan/nan.h:25:0,
	                 from ../src/utilities.cc:4:
	/home/originalexe/.node-gyp/4.1.2/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
	 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
	                                        ^
	/home/originalexe/.node-gyp/4.1.2/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
	/home/originalexe/.node-gyp/4.1.2/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
	 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
	                                        ^
	/home/originalexe/.node-gyp/4.1.2/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
	In file included from ../src/utilities.cc:4:0:
	../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
	../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
	     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
	                                                             ^
	../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
	../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
	     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
	            ^
	make: *** [Release/obj.target/sharp/src/utilities.o] Error 1
	make: Leaving directory `/var/www/playground/node_modules/image-resizer/node_modules/sharp/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
	gyp ERR! stack     at emitTwo (events.js:87:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 3.19.0-26-generic
	gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /var/www/playground/node_modules/image-resizer/node_modules/sharp
	gyp ERR! node -v v4.1.2
	gyp ERR! node-gyp -v v3.0.3
	gyp ERR! not ok 
	npm ERR! Linux 3.19.0-26-generic
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "image-resizer"
	npm ERR! node v4.1.2
	npm ERR! npm  v2.14.4
	npm ERR! code ELIFECYCLE

	npm ERR! sharp@0.10.1 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the sharp@0.10.1 install script 'node-gyp rebuild'.
	npm ERR! This is most likely a problem with the sharp package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls sharp
	npm ERR! There is likely additional logging output above.

**Comment by jimmynicol** [comment]
that looks like a `sharp` issue with node `v4.1.2`. As a temporary workaround I would suggest setting the node engine in your package.json to `v.0.12.7`.

I will check into issues with `v4.1.2`.

**Comment by OriginalEXE** [comment]
Actually, I had the same issue with the latest 0.12.x version of node. I opened this ticket 29 days ago and I was not running a node 4.x back then, it was only released.

I don't think you need to lose time on figuring this out though, if you will bump the sharp version in the new version, it will work fine as that's what I did to get sharp to build.

**Comment by jimmynicol** [comment]
OK good to know. New version coming up soon, just working on your other issue #72
