### ISSUE TITLE
Last-Modified header is missing?

### ISSUE THREAD

**Issue by jgillman** [jimmynicol/image-resizer#74]
I might have something configured incorrectly but I'm not seeing `Last-Modified` being sent in the response.

Best case they're just missing and that's fine. Worst case it's missing and interpreted as `Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT`.

---

At the moment it seems to be screwing up Facebook's bot that grabs images for when a user shares a link. There is [an open bug on Facebook](https://developers.facebook.com/bugs/388405488023104/) where several users (including myself) are having image loading issues that look like they're related to the `Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT`.

**Comment by jimmynicol** [comment]
@jgillman take a look at this: https://github.com/jimmynicol/image-resizer/blob/master/src/streams/response.js#L77

So if you are not running dev mode then you will be sending the appropriate headers for caching, which includes the `Last-Modified` header. It is indeed set to 1/1/1970 which represents `Date(0)` in unixtime and it would appear that Facebook is being bit by a simple bug that 0 cant represent false.

I will set this expiry to something less annoying.

**Comment by jimmynicol** [comment]
Try out `v1.2.1` for this change.

**Comment by jgillman** [comment]
Great! Thank you. I'll test it out this week and give a shout if FB isn't
happy with it ;)
