### ISSUE TITLE
Black background when converting png to jpg

### ISSUE THREAD

**Issue by dottodot** [jimmynicol/image-resizer#75]
When I convert a png to jpg the transparent parts of the image turn black and the rest of the image's colours get messed up. Is there anyway to define the background colour so that this doesn't happen?

**Comment by jimmynicol** [comment]
`image-resizer` is not supposed to deal with converting image types, it is merely designed to resize and optimize existing images. Furthermore png and jpgs are not compatible types especially when it comes to alpha transperancy, jpg does not support it at all.
