### ISSUE TITLE
Using it for s3  compatible third party buckets (but not provided by amazon)

### ISSUE THREAD

**Issue by shroukkhan** [jimmynicol/image-resizer#77]
Hi,
Is it possible to configure the module to use s3 buckets which are compatible with amazon, but provided by someone else.

for example, I am using my local provider with the following settings

AWS_ACCESS_KEY_ID=xxxxx
AWS_SECRET_ACCESS_KEY=xxxxx
AWS_REGION=s.qstack.advania.com
S3_BUCKET=atrius-is-production
PORT=3003
LOCAL_FILE_PATH=/home/khan/my_fancy_image_server/node_modules/image-resizer

which is not working because the requests are sent to wrong URL

[resizer] Inaccessible host: `atrius-is-production.s3.s.qstack.advania.com.amazonaws.com'. This service may not be available in the`s.qstack.advania.com' region. 
GET /test.png 500 190.996 ms - -

How to update the 's3.s.qstack.advania.com.amazonaws.com' part using some kind of configuration ?

**Comment by jimmynicol** [comment]
This sounds like an issue with the `aws-sdk` and not something with `image-resizer`. It is possible that this sort of setup is not supported by the sdk or at least the current version of it. To be honest I was not aware this was even possible with AWS.

**Comment by shroukkhan** [comment]
Hi,i forgot to update this. Yes, it was indeed an issue with the s3 provider. they did not manage the images well. all worked well after they fixed their end .
