### ISSUE TITLE
Update sharp dependency to v0.12.0

### ISSUE THREAD

**Issue by leesiongchan** [jimmynicol/image-resizer#81]
It switches default interpolator to bicubic, which could greatly improve the quality significantly and resolves issue #70

**Comment by ernestopye** [comment]
+1 - this also seems to solve some issues while attempting to install sharp on Windows.

**Comment by OriginalEXE** [comment]
+1

**Comment by leesiongchan** [comment]
We've bumped sharp to v0.15 in tripviss/image-resizer#2
