### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by risul** [jimmynicol/image-resizer#90]
@jimmynicol is this project dead?
5 months since there was any activity while there are multiple pull requests pending for your comment/approval!

If you nead any help maintaining the project, please let us know :)

Thanks!

**Comment by francesconero** [comment]
:+1:

**Comment by leesiongchan** [comment]
Since the maintainer is unresponsive, we've decided to maintain our own fork at https://github.com/tripviss/image-resizer
